### ISSUE TITLE
syntax-error building fedora branch on f23

### ISSUE THREAD

**Issue by lsm5** [projectatomic/container-selinux#11]
```
gawk: fatal: cannot open file `/etc/selinux/config' for reading (Permission denied)
docker.if:131: Error: duplicate definition of apache_exec(). Original definition on 277.
gawk: fatal: cannot open file `/etc/selinux/config' for reading (Permission denied)
Compiling  docker module
/usr/bin/checkmodule:  loading policy configuration from tmp/docker.tmp
docker.te:296:ERROR 'syntax error' at token 'systemd_dbus_chat_machined' on line 14602:
    systemd_dbus_chat_machined(docker_t)
#line 296
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
/usr/share/selinux/devel/include/Makefile:154: recipe for target 'tmp/docker.mod' failed
make: *** [tmp/docker.mod] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.EbpwOG (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.EbpwOG (%build)
```

**Comment by rhatdan** [comment]
Use the RHEL7-1.10 branch for building on F23

**Comment by lsm5** [comment]
new one with `rhel-1.10` branch:

    gawk: fatal: cannot open file `/etc/selinux/config' for reading (Permission denied)
    docker.if:131: Error: duplicate definition of apache_exec(). Original definition on 277.
    gawk: fatal: cannot open file `/etc/selinux/config' for reading (Permission denied)
    Compiling  docker module
    /usr/bin/checkmodule:  loading policy configuration from tmp/docker.tmp
    docker.te:428:ERROR 'unknown type svirt_sandbox_domain' at token ';' on line 20713:
    #line 428
        typeattribute svirt_sandbox_domain can_dump_kernel;
    /usr/bin/checkmodule:  error(s) encountered while parsing configuration
    /usr/share/selinux/devel/include/Makefile:154: recipe for target 'tmp/docker.mod' failed
    make[1]: *** [tmp/docker.mod] Error 1
    make[1]: Leaving directory '/home/lsm5/repositories/pkgs/docker/BUILD/docker-8eaba084fd648fa35dfb89069a318251e115c6f3/docker-selinux-39c092ce65cc68c86197d1e2f1a7d64abaf3203e'
    Makefile:13: recipe for target 'docker.pp' failed
    make: *** [docker.pp] Error 2
    error: Bad exit status from /var/tmp/rpm-tmp.88Xplh (%build)

**Comment by lsm5** [comment]
@rhatdan, did you get a chance to check out ^ ?

**Comment by rhatdan** [comment]
I updated the policy could you try again.
