### ISSUE TITLE
error building master branch on rhel 7.3

### ISSUE THREAD

**Issue by lsm5** [projectatomic/container-selinux#15]
@rhatdan @wrabcak ptal

```
 Compiling targeted docker module
/usr/bin/checkmodule:  loading policy configuration from tmp/docker.tmp
docker.te:277:ERROR 'syntax error' at token 'fs_rw_nsfs_files' on line 11984:
fs_rw_nsfs_files(docker_t)

/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make[1]: *** [tmp/docker.mod] Error 1
make[1]: Leaving directory `/home/lsm5/repositories/pkgs/docker/BUILD/docker-f9d4a2c183cb4ba202babc9f8649ea043d8c84d0/docker-selinux-dba8e033744889ffc44e5ddc68ce55e27d0e619c'
make: *** [docker.pp] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.U0ERwG (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.U0ERwG (%build)`



$ rpm -q selinux-policy
selinux-policy-3.13.1-93.el7.noarch
```

**Comment by lsm5** [comment]
@rhatdan @wrabcak I don't see fs_rw_nsfs_files defined anywhere /usr/share/selinux/devel/include with selinux-policy-3.13.1-93.el7.noarch. Is that the right reason for this issue?

**Comment by rhatdan** [comment]
Yes we need an updated version of selinux-policy with that interface, or we need to carry it ourselves.

**Comment by rhatdan** [comment]
@wrabcak Could you fix this?

**Comment by lsm5** [comment]
@rhatdan is this something I could just include in docker.if or another interface file in docker-selinux ? Might be a much quicker fix than spinning up a new selinux-policy?

**Comment by lsm5** [comment]
@rhatdan @wrabcak I added https://github.com/lsm5/docker-selinux/commit/e543d2ee2e8c36624ea9fc6a77339eb2c02b141d and now it's erroring out `syntax error at token 'virt_stub_svirt_sandbox_file'`. Seems like I don't hit the original issue anymore, so let me know if it's ok to proceed.

**Comment by ssekidde** [comment]
@lsm5 that stub interface is missing as well in RHEL7 and needs to be added.

**Comment by lsm5** [comment]
@ssekidde hi, RE: nsfs I just copied that over from tracefs that I found in kernel/filsystems.if, but not sure how to proceed with stub interface. Could you please add them both in selinux-policy and update the rpm, docker 7.3 builds are blocked on this currently

**Comment by ssekidde** [comment]
@lsm5 both interfaces will have to be added by @wrabcak in selinux-policy. Does a BZ exist?
For testing purposes see if you can try to add this to docker.if 

########################################
## <summary>
##      svirt_sandbox_file_t stub interface.  No access allowed.
## </summary>
## <param name="domain" unused="true">
##      <summary>
##      Domain allowed access.
##      </summary>
## </param>
#
interface(`virt_stub_svirt_sandbox_file',`
        gen_require(`
                type svirt_sandbox_file_t;
        ')
')

**Comment by lsm5** [comment]
On Thu, Sep 01, 2016 at 11:59:07AM -0700, Simon Sekidde wrote:
> @lsm5 both interfaces will have to be added by @wrabcak in selinux-policy. Does a BZ exist?
> For testing purposes see if you can try to add this to docker.if 
> 
> ########################################
> ## <summary>
> ##      svirt_sandbox_file_t stub interface.  No access allowed.
> ## </summary>
> ## <param name="domain" unused="true">
> ##      <summary>
> ##      Domain allowed access.
> ##      </summary>
> ## </param>
> #
> interface(`virt_stub_svirt_sandbox_file',`
>         gen_require(`
>                 type svirt_sandbox_file_t;
>         ')
> ')

Dan added a temporary fix for this in docker-selinux itself. I'll file a bz
for selinux-policy.

-- 
Lokesh
Freenode: lsm5
GPG: 0xC7C3A0DD

**Comment by rhatdan** [comment]
Yes we can just hack the docker.te until we have these interfaces in the selinux-policy package.

**Comment by wrabcak** [comment]
Sorry for delay. Problem here is quite bigger. We don't have labeling for nsfs filesystem in rhel-7.3. @lsm5  could you create BZ to add this interface to selinux-policy on rhel-7.3 ? I assume this is blocker for you guys.
Thanks.

**Comment by rhatdan** [comment]
@wrabcak We worked around it by embedding the code into docker.te.  We actually need to interfaces to remove this hack.
https://github.com/projectatomic/docker-selinux/commit/45be23048bbdfa691e2a7b2ec67bda3922f09667

**Comment by lsm5** [comment]
@wrabcak https://bugzilla.redhat.com/show_bug.cgi?id=1372705

**Comment by rhatdan** [comment]
Fixed in current release.
