### ISSUE TITLE
build failure with commit 51001dd on rhel 7.3

### ISSUE THREAD

**Issue by lsm5** [projectatomic/container-selinux#18]
Compiling targeted container module
/usr/bin/checkmodule:  loading policy configuration from tmp/container.tmp
container.te:390:ERROR 'syntax error' at token 'virt_sandbox_domtrans' on line 19871:
# line 390

```
virt_sandbox_domtrans(container_runtime_t, spc_t)
```

/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make[1]: **\* [tmp/container.mod] Error 1
make[1]: Leaving directory `/home/lsm5/repositories/pkgs/docker/BUILD/docker-5759a0805380f1067386e87b64f0e27ed818be27/container-selinux-51001dd9052288a6f2356db61bcf4a3084497366'
make: **\* [container.pp] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.LwRSQv (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.LwRSQv (%build)

**Comment by lsm5** [comment]
@rhatdan

**Comment by lsm5** [comment]
this might be due to an older selinux-policy on my system

**Comment by rhatdan** [comment]
Yes make sure you have the latest selinux-policy package.

**Comment by rhatdan** [comment]
If it is not there we will have to branch container-selinux for this feature.

**Comment by lsm5** [comment]
So, I have selinux-policy-3.13.1-102.el7_3.1.noarch and I still see this issue.

**Comment by rhatdan** [comment]
Ok so this is probably not in the selinux-policy package.  I will create a RHEL branch and we can get this fixed in rhel7.4

**Comment by rhatdan** [comment]
RHEL-1.12 branch should work.

**Comment by lsm5** [comment]
ok, testing ....

**Comment by rhatdan** [comment]
Fixed in current release
