### ISSUE TITLE
container-selinux-2.10-1.el7.noarch conflicts with docker-engine-selinux-17.03.0.ce-1.el7.centos

### ISSUE THREAD

**Issue by mlcooper** [projectatomic/container-selinux#35]
When doing a `yum install docker-engine-1.13.1-1.el7.centos`, it installs a dependency package called `docker-engine-selinux-17.03.0.ce-1.el7.centos` (for some reason instead of `docker-engine-selinux-1.13.1-1.el7.centos`.

Afterward, when I try to do a `yum install container-selinux-2.10-1.el7.noarch` from the `RHEL-1.12` branch, I get an error:
```
Error: docker-engine-selinux conflicts with container-selinux-2.10-1.el7.noarch
```
If I install `container-selinux-2.10-1.el7.noarch` first and then do a  `yum install docker-engine-1.13.1-1.el7.centos`, I also get a conflict error.

I found out that there's a `>=` in here which is why 1.13 pulls the newer 17.x as a dependency:
```
[root@n7-z01-0a2a0574 ~]# yum deplist docker-engine-1.13.1-1.el7.centos
package: docker-engine.x86_64 1.13.1-1.el7.centos
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-21.el7_3
  dependency: device-mapper-libs >= 1.02.90-1
   provider: device-mapper-libs.x86_64 7:1.02.135-1.el7_3.3
   provider: device-mapper-libs.i686 7:1.02.135-1.el7_3.3
  dependency: docker-engine-selinux >= 1.13.1-1.el7.centos
```

Does https://github.com/projectatomic/container-selinux/tree/RHEL-1.12 need to be updated to support docker-engine-selinux-17.xx.x?

**Comment by rhatdan** [comment]
No docker-engine-selinux should go away, and they should just use container-selinux.

This is a bug in docker-engine-selinux in that it conflicts with a package from the distribution.
