### ISSUE TITLE
Accessing Host IPC through a sandbox container (Pod) doesn't work with SELinux

### ISSUE THREAD

**Issue by filbranden** [projectatomic/container-selinux#48]
Hi @rhatdan,

This is somewhat related to #46 but when using "Host IPC" in which the IPC is shared with the actual host the container is running on. (Implemented in Docker by using `--ipc host` mode.)

The way Pod's are implemented in Kubernetes is to run a "sandbox" container that "owns" the network and IPC namespaces and then have other containers in that Pod refer to that container's settings. In other words, the sandbox container will be run with `--ipc host` while the other containers will be run with `--ipc container:<sandbox>` so they share that one.

But running things this way makes `ipcs` command (from busybox!) fail on the non-sandbox container, causing an AVC while trying to access specific entries of IPC from the host.

For a simple reproducer:

1. Create IPCs on the host:

```
        $ ipcmk -M 1M -S 10 -Q
        Shared memory id: 98304
        Message queue id: 65536
        Semaphore id: 131072
```

2. Run a "sandbox" container to define a Pod, have it run on Host IPC mode so it can access the IPCs created above:

```
        $ docker run --name hostipc_pod --detach --ipc host busybox sleep 3600
```

3. Run a separate container that shares the sandbox's IPC and try to check `ipcs` output there (using busybox and after #47 has been applied!):

```
        $ docker run --ipc container:hostipc_pod busybox ipcs

        ------ Message Queues --------
        key        msqid      owner      perms      used-bytes   messages

        ------ Shared Memory Segments --------
        key        shmid      owner      perms      bytes      nattch     status

        ------ Semaphore Arrays --------
        key        semid      owner      perms      nsems

```

The expectation was that the IPCs created above would show up here, but they don't, the output is empty.

This only happens when Host IPC is in use. Otherwise, when containers are sharing IPC with a sandbox, this doesn't seem to be an issue...

Checking for violations shows them in the Audit log:

```
        $ grep AVC /var/log/audit/audit.log
        type=AVC msg=audit(1516822236.932:1618): avc:  denied  { unix_read } for  pid=19972 comm="ipcs" key=39206617  scontext=system_u:system_r:container_t:s0:c374,c410 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=msgq permissive=0
        type=AVC msg=audit(1516822236.932:1619): avc:  denied  { unix_read } for  pid=19972 comm="ipcs" key=-1093557504  scontext=system_u:system_r:container_t:s0:c374,c410 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
        type=AVC msg=audit(1516822236.932:1620): avc:  denied  { unix_read } for  pid=19972 comm="ipcs" key=-125885918  scontext=system_u:system_r:container_t:s0:c374,c410 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=sem permissive=0
```

The expected output would be:

```
        $ docker run --ipc container:hostipc_pod busybox ipcs

        ------ Message Queues --------
        key        msqid      owner      perms      used-bytes   messages
        0x02563ed9 65536      5192       644        0            0

        ------ Shared Memory Segments --------
        key        shmid      owner      perms      bytes      nattch     status
        0xbed1a300 98304      5192       644        1048576    0

        ------ Semaphore Arrays --------
        key        semid      owner      perms      nsems
        0xf87f2222 131072     5192      644        10
```

/cc @Random-Liu since this came up in kubernetes/kubernetes#58174

**NOTE:** Perhaps by just testing `ipcs` I'm missing something, it's possible that after fixing this, `ipcs` will show them, but they won't be usable? Perhaps there needs to be more investigation there...

**Comment by rhatdan** [comment]
The unix_read you are showing above looks like a bug in docker, since when using --ipc=host, it is supposed to launch the container without container separation, IE Run the container with spc_t.
